apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: entered-workflowtemplate
  namespace: user1
spec:
  templates:
  - name: main
    steps: 
    - - name: functionC
        template: functionC
    - - name: functionD
        template: functionD
  - name: functionC
    http:
      url: http://entered-service1.user1.192.168.10.146.nip.io
      method: POST
      headers: 
      - name: Content-Type
        value: application/json
  - name: functionD
    http: 
      url: http://entered-service2.user1.192.168.10.146.nip.io
      method: POST
      headers: 
      - name: Content-Type
        value: application/json
