apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trigger
  namespace: user1
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: storage-event
      eventSourceName: storage-event
      eventName: upload
    - name: entered-event
      eventSourceName: entered-event
      eventName: entered
  triggers:
    - template:
        conditions: "storage-event"
        name: upload-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: storage-upload-workflow-
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: main
                workflowTemplateRef:
                  name: storage-upload-workflowtemplate
    - template:
        conditions: "entered-event"
        name: entered-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: entered-workflow-
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: main
                workflowTemplateRef:
                  name: entered-workflowtemplate

